---
swagger: "2.0"
info:
  description: "for NLP"
  version: "1.0.0"
  title: "NLP"
  termsOfService: ""
  contact:
    name: "Developer Gavin"
    email: "gavin19950511@gmail.com"
  license:
    name: "Apache 2.0"
host: "140.115.126.216:8082"
basePath: "/NLP"
tags:
- name: "speechAnalysis"
  description: "for CLAS"
- name: "checkStatus"
  description: "for option method"
schemes:
- "http"
paths:
  /speech/score:
    post:
      tags:
      - "speechAnalysis"
      summary: ""
      description: ""
      operationId: "speech_score_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/speech"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/scoreAnalysisResult"
      x-swagger-router-controller: "swagger_server.controllers.speech_analysis_controller"
    options:
      tags:
      - "checkStatus"
      summary: ""
      description: ""
      operationId: "speech_score_options"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/serverStatusRespond"
      x-swagger-router-controller: "swagger_server.controllers.check_status_controller"
  /speech/emotion:
    post:
      tags:
      - "speechAnalysis"
      summary: ""
      description: ""
      operationId: "speech_emotion_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/speech"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/sentence"
      x-swagger-router-controller: "swagger_server.controllers.speech_analysis_controller"
    options:
      tags:
      - "checkStatus"
      summary: ""
      description: ""
      operationId: "speech_emotion_options"
      parameters: []
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
              default: "*"
          schema:
            $ref: "#/definitions/serverStatusRespond"
      x-swagger-router-controller: "swagger_server.controllers.check_status_controller"
  /speech/fiveDivisions:
    post:
      tags:
      - "speechAnalysis"
      summary: ""
      description: ""
      operationId: "speech_five_divisions_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/speech"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/fiveDivisionsResult"
      x-swagger-router-controller: "swagger_server.controllers.speech_analysis_controller"
    options:
      tags:
      - "checkStatus"
      summary: ""
      description: ""
      operationId: "speech_five_divisions_options"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/serverStatusRespond"
      x-swagger-router-controller: "swagger_server.controllers.check_status_controller"
definitions:
  word:
    type: "object"
    required:
    - "content"
    properties:
      content:
        type: "string"
      word2vec:
        type: "number"
      emotion:
        type: "number"
    example:
      emotion: 6.02745618307040320615897144307382404804229736328125
      word2vec: 0.80082819046101150206595775671303272247314453125
      content: "content"
  sentence:
    type: "object"
    required:
    - "source"
    properties:
      source:
        type: "string"
      wordArray:
        type: "array"
        items:
          $ref: "#/definitions/word"
      top10:
        type: "array"
        items:
          type: "string"
      emotion:
        type: "number"
    example:
      top10:
      - "something keyword"
      - "something keyword"
      - "something words"
      - "something words"
      - "something words"
      - "something words"
      wordArray:
      - "something keyword"
      - "something words"
      - "something keyword"
      - "something words"
      - "something words"
      - "something words"
      source: "source"
      emotion: "-1.22"
  speech:
    type: "object"
    required:
    - "source"
    properties:
      source:
        type: "string"
      topic:
        type: "string"
    example:
      source: "用基因改造的馬鈴薯餵食老鼠會讓老鼠出現健康問題，還有為期兩年的基因改造玉米餵食老鼠試驗中，他與同仁發現基改玉米NK603與除草劑年年春都會讓老鼠提早長出更多的腫瘤，都證明沒有人可以保證基改對人類完全有益無壞，那它是危險的，自然大家不接受它，市場也會排斥它，就不會有需求了"
      topic: "基改食品的出現，固然出自於商業化的利益考量，但最初的動力其實就是為了解決問題，就像這次的基改馬鈴薯，最初的研發目的就是為了降低馬鈴薯製品中可能會對健康有疑慮的丙烯醯胺（儘管丙烯醯胺是否真的有危害，目前尚不清楚），其實是站在健康利益的考量，然而民眾對於基改食品的不了解與妖魔化，加上媒體的過分渲染，才演變成今日看到基改就喊打的現象。至於許多人提出的質疑，認為基改作物會傷害環境，例如有抗除草劑基因的黃豆會污染傳統黃豆，或者會讓農民無形中噴灑過量除草劑，進而損害環境，不過從剛才的表格就可以得知，此次基改馬鈴薯所使用的轉殖基因，皆是原本就存在於馬鈴薯中的基因，與除草劑的案例其實不能相提並論。"
  scoreAnalysisResult:
    type: "object"
    properties:
      score:
        type: "number"
      pass:
        type: "boolean"
      source:
        $ref: "#/definitions/sentence"
    example:
      score: "18.7"
      pass: 1
      source:
        source: "some text is here."
  fiveDivisionsResult:
    type: "object"
    properties:
      highToLow:
        type: "array"
        items:
          type: "integer"
      scoreDivision:
        type: "array"
        items:
          type: "number"
      nameDivision:
        type: "array"
        items:
          type: "string"
      pass:
        type: "boolean"
      source:
        $ref: "#/definitions/sentence"
    example:
      highToLow:
      - 4
      - 0
      - 1
      - 3
      - 2
      scoreDivision:
      - 18.699999999999999289457264239899814128875732421875
      - 12
      - 0
      - 2
      - 26.699999999999999289457264239899814128875732421875
      nameDivision:
      - "民眾"
      - "政府"
      - "企業"
      - "專家"
      - "其他"
      score: "18.7"
      pass: 1
      source:
        source: "some text is here."
  requestsErrorRespond:
    type: "object"
    properties:
      code:
        type: "string"
      text:
        type: "string"
    example:
      code: "404"
      text: "rare word"
  serverStatusRespond:
    type: "object"
    properties:
      code:
        type: "string"
      text:
        type: "string"
    example:
      code: "200"
      text: "working"
